name : Kurian K S
title: Hi there, I'm Kurian K S
email: ksk.steve@gmail.com
description: An open source Enthusiast, who keeps logic and learning core to heart. In my free time try complete my bucket list of adventures.
twitter_username: kskurian
github_username:  kskurian
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed